### ISSUE TITLE
eklenecekler

### ISSUE THREAD

**Issue by ademilter** [ademilter/akaryakit-fiyatlari#1]
BP
https://www.bp.com/tr_tr/turkey/home/urun-ve-hizmetler/akaryakit-ve-pompa-fiyatlari.html
api: https://www.bp.com/bp-tr-pump-prices/api/PumpPrices?strCity=KAHRAMANMARAŞ

alpet
html parse: https://www.alpet.com.tr/tr-TR/akaryakit-fiyatlari?city=ADANA

türkiye petrolleri
html parse: https://www.tppd.com.tr/antalya-akaryakit-fiyatlari

**Comment by alperbayram** [comment]
selamlar adem abi ben de böyle bir şey üzerinde çalışmak istiyordum dikkatimi çekti ve bp ekledim kontrol eder misin?

**Comment by ademilter** [comment]
Selam @alperbayram 
Teşekkürler, diğer ikisini de ben eklemiştim. Eline sağlık
